const urlConstants = {
  GET_USER_LIST_URL: "api/v1/admin/user/",
  GET_USER_URL: "api/v1/user/",
  RE_FRESH_URL: "api/v1/admin/refresh-token/",
  LOGIN_URL: "api/v1/admin/login/",
  GET_WORK_TYPE_URL: "api/v1/admin/worktype/common/",
  GET_EDUCATION_URL: "api/v1/admin/education/",
  FETCH_EDUCATION_URL: "api/v1/common/education/",
  FETCH_ROLES_URL: "api/v1/common/roles/",
  GET_ROLES_URL: "api/v1/admin/role/",
  FETCH_UNIT_URL: "api/v1/common/units/",
  GET_UNIT_URL: "api/v1/admin/unit/",
  GET_SERVICES_URL: "api/v1/admin/service/",
  GET_BRAND_URL: "api/v1/admin/brands/",
  GET_CATEGORY_URL: "api/v1/admin/category/",
  GET_SUPPLIER_URL: "api/v1/admin/supplier/",
  GET_SUB_CATEGORY_URL: "api/v1/admin/category/sub_category/",
  GET_BRAND_PRODUCT_URL: "api/v1/admin/brandproduct/",
  GET_PRODUCT_URL: "api/v1/admin/products/",
  GET_ORDER_URL: "api/v1/admin/order/",
  GET_TRACK_URL: "api/v1/admin/order_track/",
  GET_PROJECT_URL: "api/v1/admin/project/",
  GET_BUDGET_URL: "api/v1/admin/budget/",
  GET_BRAND_SUPPLIER_URL: "api/v1/admin/brandsupplier/",
};
export default urlConstants;
